(function(g){var window=this;var s7=function(a,b){return g.aa[a]=b},Mta=function(a,b){var c=new g.Aj;
c.o=a.o;c.D=a.D;c.C=a.C;c.B=a.B;c.isDefault=!1;c.G=a.G;c.F=a.F;c.H=a.H;c.g=b;return c},t7=function(a){return a.g?a.g.languageCode:a.o},u7=function(a){var b={format:a.A,
languageCode:a.o,languageName:a.D,displayName:g.Bj(a),kind:a.B,name:a.C,id:a.za,is_servable:a.M,is_default:a.isDefault,is_translateable:a.G,vss_id:a.F};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},v7=function(a){if(!Nta.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Ota,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},Pta=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},Qta=function(a){for(var b in a)delete a[b]},Rta=function(){},x7=function(a){this.F=a;
this.B=this.o=this.mode=this.A=0;this.C=new w7(this);this.D=new w7(this);this.g=[];this.clear()},Tta=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Nl:a,
Ol:b,result:0};a=Sta[a];b=Sta[b];if(a&128){if(!(b&128)&&0!=c.g&&c.o==b)return{Nl:a,Ol:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Nl:a,Ol:b,result:2};return{Nl:a,Ol:b,result:3}},Vta=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.B&&a.reset(),a.C.g.clear(),a.D.g.clear()):(a.B=0,Uta(a.C,b,c,d))},Wta=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.o=d.time;0==d.type?Vta(a,d.gv,d.hv,b):1==d.type&&a.A&496&&Uta(a.D,d.gv,d.hv,b)}a.g.length=0},y7=function(){this.g=0},z7=function(){this.o=this.A=this.g=0},A7=function(){this.timestamp=this.cf=0;
this.g=!1},B7=function(a){this.A=[];
for(var b=0;15>=b;b++){this.A[b]=[];for(var c=0;32>=c;c++)this.A[b][c]=new A7}this.g=this.o=this.Ec=0;this.style=new y7;this.C=a;this.B=0},C7=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.C.o+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.A[m][q];
if(0!=r.cf){0==c&&(c=m,d=q);var n=String.fromCharCode(r.cf),u=r.timestamp;u<e&&(e=u);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.cf||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.o+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.A[k][m],r=q.cf,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32==m||0==r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},aua=function(a,b){switch(a){case 0:return Xta[(b&127)-32];
case 1:return Yta[b&15];case 2:return Zta[b&31];case 3:return $ta[b&31]}return 0},D7=function(a){return a.A[a.Ec][a.o]},E7=function(a,b,c){2<=b&&1<a.o&&(--a.o,D7(a).cf=0);
var d=D7(a);d.timestamp=a.C.o+0;d.cf=aua(b,c);32>a.o&&a.o++},bua=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.A[b+e][f].jm(a.A[c+e][f])},F7=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},G7=function(a){a.Ec=0<a.g?a.g:1;
a.o=1;F7(a,0,15)},H7=function(a){this.B=a;
this.C=0;this.style=new y7;this.D=new B7(a);this.F=new B7(a);this.G=new B7(a);this.o=this.D;this.A=this.F;this.g=this.o},I7=function(a,b,c){var d=a.o,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:C7(d,c),G7(a.o),G7(a.A),d.Ec=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.B.mode=1<<d.B;e?d.o=1:d.g!=b&&(d.g>b?(C7(d,c),F7(d,d.Ec-d.g,b)):d.Ec<b&&(b=d.g),d.g=b)},cua=function(a){a.style.set(1);
a.g=a.A;a.g.g=0;a.g.style=a.style;a.B.mode=1<<a.g.B},dua=function(a){a.style.set(4);
a.g=a.G;a.g.style=a.style;a.B.mode=1<<a.g.B},w7=function(a){this.o=a;
this.g=new z7;this.C=0;this.A=new H7(a);this.D=new H7(a);this.B=this.A},Uta=function(a,b,c,d){a.g.update();
b=Tta(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Nl;c=b.Ol;if(32<=e||!e)a.o.mode&a.o.A&&(b=e,b&128&&(b=127),c&128&&(c=127),e=a.B.g,b&96&&E7(e,0,b),c&96&&E7(e,0,c),!a.o.F&&0!=b&&0!=c&&3==e.style.g&&C7(e,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.A=e,b.o=c,b.g=2,b=e&8?a.D:a.A,a.B=b,a.o.mode=1<<(a.C<<2)+(b.C<<1)+(4==b.style.g?1:0),(a.o.mode|1<<(a.C<<2)+(b.C<<1)+(4!=b.style.g?1:0))&a.o.A))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&
14)>>1):0;c=b.g;switch(b.style.get()){case 4:d=c.Ec;break;case 3:if(d!=c.Ec){if(d<c.g&&(d=c.g,d==c.Ec))break;var f=1+c.Ec-c.g,k=1+d-c.g;bua(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));F7(c,b,e)}}c.Ec=d;c.o=a+1}else switch(e&7){case 1:switch(c&112){case 32:E7(b.g,0,32);break a;case 48:57==c?(b=b.g,D7(b).cf=0,32>b.o&&b.o++):E7(b.g,1,c&15)}break;case 2:c&32&&E7(b.g,2,c&31);break;case 3:c&32&&E7(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:cua(b);break;
case 33:b=b.g;1<b.o&&(--b.o,D7(b).cf=0);break;case 36:b=b.g;d=D7(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.A[a][c]==d){for(;32>=c;c++)b.A[a][c].reset();break}break;case 37:I7(b,2,d);break;case 38:I7(b,3,d);break;case 39:I7(b,4,d);break;case 40:E7(b.g,0,32);break;case 41:b.style.set(2);b.g=b.o;b.g.g=0;b.g.style=b.style;b.B.mode=1<<b.g.B;break;case 42:d=b.G;d.g=15;d.style.set(4);G7(d);dua(b);break;case 43:dua(b);break;case 44:a=b.o;switch(b.style.get()){case 1:case 2:case 3:C7(a,d)}F7(a,0,15);break;
case 45:b:{a=b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.Ec){++a.Ec;a.o=1;break b}case 3:}2>a.g&&(a.g=2,a.Ec<a.g&&(a.Ec=a.g));b=a.Ec-a.g+1;C7(a,d);bua(a,b,b+1,a.g-1);F7(a,a.Ec,1)}break;case 46:F7(b.A,0,15);break;case 47:C7(b.o,d);d=b.A;a=b.B.o+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.A[c][e].timestamp=a;d=b.A;b.A=b.o;b.o=d;cua(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.o+=c&3)&&(b.o=32)}}},J7=function(){this.wa=[]},eua=function(){this.A=[];
this.g=[];this.o=-1},K7=function(a,b){return b?a.g.concat(a.A):a.g},L7=function(a,b){switch(b.B){case "asr":fua(b,a.A);
break;default:if(b.isDefault||0>a.o)a.o=a.g.length;fua(b,a.g)}},fua=function(a,b){g.we(b,(0,g.B)(a.J,a))||b.push(a)},gua=function(a,b){var c=g.ve(a.g,(0,g.B)(b.J,b));
-1!=c&&(a.o=c)},M7=function(){},N7=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.Nr.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.B=f;this.o=k},O7=function(a,b,c,d,e){g.Nr.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},Q7=function(a){a=void 0===a?{}:a;
var b="_"+P7++;return new O7(0,0x8000000000000,0,b,a)},R7=function(a){this.A=a;
this.o=null},iua=function(a,b,c){var d=a.getAttribute("t"),d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0),e=a.getAttribute("d"),e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);
b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?S7.ip:S7.Cl;a=g.Et("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");hua(d,e,k,b,f,a.firstChild,{},c)},hua=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.pr=!0;break;case "u":k.Is=!0;break;case "font":var m=f.getAttribute("color");T7.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new N7(a,b,c,d,n.nodeValue,e||0<m,g.Hb(k)?void 0:k));else{var q={};g.za(q,k);hua(a,b,c,d,e||0<m,n,q,l)}}},U7=function(a){this.o={};
this.C={};this.D={};this.A="_"+P7++;this.B=a},V7=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},W7=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},X7=function(a,b){var c=V7(a,b);
if(void 0!=c)return c},Y7=function(a,b){var c=a.getAttribute(b);
if(null!=c)return T7.test(c),c},jua=function(a,b){var c={},d=b.getAttribute("ws");
g.za(c,d?a.D[d]:a.B);d=X7(b,"mh");null!=d&&(c.wr=d);d=X7(b,"ju");null!=d&&(c.textAlign=d);d=X7(b,"pd");null!=d&&(c.tj=d);d=Y7(b,"wfc");null!=d&&(c.windowColor=d);d=V7(b,"wfo");void 0!=d&&(c.zj=d/255);return c},kua=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.za(c,a.C[d]);d=X7(b,"ap");null!=d&&(c.Fg=d);d=V7(b,"cc");null!=d&&(c.Cv=d);d=V7(b,"ah");null!=d&&(c.Ph=d);d=V7(b,"rc");null!=d&&(c.Nn=d);d=V7(b,"av");null!=d&&(c.Xh=d);return c},lua=function(a,b,c){var d={};
g.za(d,kua(a,b));g.za(d,jua(a,b));c?Pta(d,a.B)?(c=a.A,d=a.B):c="_"+P7++:c=b.getAttribute("id")||"0";a=V7(b,"t");b=V7(b,"d")||0x8000000000000;return new O7(a,b,0,c,d)},Z7=function(a,b,c){this.F=c;
this.version=this.C=this.D=this.g=0;this.o=new window.DataView(a);this.A=[]},$7=function(a){var b=a.g;
a.g+=1;return a.o.getUint8(b)},mua=function(a){var b=a.g;
a.g+=4;return a.o.getUint32(b)},a8=function(a,b){this.B=a;
this.o="CC3"==b.D?4:0;this.A=new x7(!1);this.A.A=1<<this.o},nua=function(a){if(!(a.g<a.o.byteLength))return!1;
var b=mua(a);b.toString(16);if(1380139777!=b)return!1;a.version=$7(a);if(1<a.version)return!1;$7(a);$7(a);$7(a);return!0},b8=function(){this.o=null},oua=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.pr=!0;break;case "u":l.Is=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new N7(b,c,d,e.id,q.nodeValue,f||0<n,g.Hb(l)?void 0:l),m.push(q),e!=a.o&&e.o.push(q);else{var r={};g.za(r,l);oua(a,b,c,d,e,!0,q,r,m)}}},c8=function(a){var b=0;
a=g.ka(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+c.value;return 1E3*b},d8=function(){this.A={};
this.o=null},g8=function(a,b,c,d,e,f){var k={};
g.za(k,b);g.za(k,a.params);g.za(k,c);var l={};g.za(l,b.gb);a.params.gb&&g.za(l,a.params.gb);g.za(l,c.gb);k.gb=l;g.W.call(this,{K:"div",Y:"caption-window",Z:{id:"caption-window-"+a.id,dir:k.tj==e8.Xo?"rtl":"ltr",tabindex:0,"aria-live":"assertive",lang:k.lang},R:[{K:"span",Y:"captions-text"}]});this.B=[];this.H=!1;this.C=a;this.F=[];this.G=[];this.Aa=e;this.va=f;this.D=null;this.N=.96*e;this.ea=.96*f;this.g=k;this.pa=c;this.A=this.ua["captions-text"];this.ia=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.J=d/360*16;this.type=f8.Uo;this.aa=this.J*pua(l);a=new g.qC(this.element,!0);g.K(this,a);a.subscribe("dragstart",this.iJ,this);a.subscribe("dragmove",this.hJ,this);a.subscribe("dragend",this.gJ,this);this.da=this.ca=0;a="";this.g.zj&&(a=v7(this.g.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.g.zj+")");b={"background-color":a,display:!1===this.g.isVisible?"none":"","text-align":qua[this.g.textAlign]};this.ia&&(b["border-radius"]=a?this.aa/
8+"px":"");g.Yt(this.element,b);switch(this.g.Fg){case 0:case 1:case 2:g.P(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.P(this.element,"ytp-caption-window-bottom")}},pua=function(a){var b=1+.25*(a.xi||0);
if(a.offset==h8.zu||a.offset==h8.Cu)b*=.8;return b},i8=function(a,b){var c={},d=b.background?b.background:a.g.gb.background,e;
if(null!=b.Ie||b.background)e=null!=b.Ie?b.Ie:a.g.gb.Ie,d=v7(d),c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")",a.ia&&(c["box-decoration-break"]="clone",c["border-radius"]=a.aa/8+"px");if(null!=b.xi||null!=b.offset)c["font-size"]=a.J*pua(b)+"px";d=1;e=b.color||a.g.gb.color;if(b.color||null!=b.gh)e=v7(e),d=null==b.gh?a.g.gb.gh:b.gh,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.yh;f==g.G3.NONE&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";
b.ov&&(k=e=b.ov);var l=a.J/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1),d=[];switch(f){case g.G3.DROP_SHADOW:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case g.G3.RAISED:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case g.G3.DEPRESSED:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case g.G3.Gu:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case g.I3.iu:e=
'"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case g.I3.nu:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case g.I3.hu:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case g.I3.CASUAL:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case g.I3.CURSIVE:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case g.I3.cp:e=g.dp()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case g.I3.Tt:case g.I3.Vo:e='Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.g.gb.offset);switch(e){case h8.zu:c["vertical-align"]="sub";break;case h8.Cu:c["vertical-align"]="super"}b.fontFamily==g.I3.cp&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.pr&&(c["font-style"]="italic");b.Is&&(c["text-decoration"]=
"underline");b.Eq&&(c.visibility="hidden");return c},rua=function(a,b,c){a.H=a.H||!!c;
var d={};g.za(d,a.g.gb);g.za(d,c||b.o);g.za(d,a.pa.gb);c=a.F[0];var e;if(c&&d.background==c.background&&d.Ie==c.Ie&&!!d.Eq==!!c.Eq&&d.yh==c.yh){var f;for(f=0;f<a.F.length;f++)if(Pta(d,a.F[f])){e=a.G[f];break}if(!e){f={};for(var k in d)d[k]!=c[k]&&(f[k]=d[k]);e=g.rd("SPAN");g.Yt(e,i8(a,f));a.G[0].appendChild(e);f=1}a.G.length=f;a.F.length=f}else a.G.length=0,a.F.length=0,e=g.rd("SPAN"),g.Yt(e,i8(a,d)),a.A.appendChild(e);a.D&&a.D.parentNode!=e&&(g.Bq(a.D),e.appendChild(a.D));c=(k=g.z(b.text))?b.text.split("\n"):
[b.text];for(f=0;f<c.length;f++){var l=c[f];if(0<f||0==a.B.length||!b.B){if(0<f||0!=a.B.length){var m=g.rd("BR");e.appendChild(m)}e.appendChild(g.vq("\u00a0"));a.D=g.vq("\u00a0");e.appendChild(a.D)}l&&(m=a.D,m.parentNode&&m.parentNode.insertBefore(k?g.vq(l):l,m))}a.F.push(d);a.G.push(e);a.B.push(b)},j8=function(a){a=void 0===a?!1:a;
g.J.call(this);this.xx=a;this.g=new eua;this.D=[];this.o=null},tua=function(a){var b={};
if(a=t7(a))b.lang=a,sua.test(a)&&(b.tj=e8.Xo);return b},uua=function(a,b,c,d,e){d=void 0===d?0:d;
e=void 0===e?0:e;if(g.z(b)){if("WEBVTT"==b.substring(0,6))return a.o||(a.o=new b8),a.o.g(b,d);b=g.Et(b);if(!b||!b.firstChild)return[];a.o||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.o=new U7(tua(c)):a.o=new d8:a.o=new R7(tua(c)));return a.o.g(b,d)}try{var f;if(g.z(b))f=!1;else{var k=new Z7(b,0,0);f=nua(k)}if(f)return a.o||(a.o=new a8(e,c)),a.o.g(b,d)}catch(l){g.Tf(l)}return[]},vua=function(a,b){return g.we(K7(a.g,!0),function(a){return a.toString()==
b})},k8=function(a,b,c,d,e,f){g8.call(this,a,b,c,d,e,f);
this.type=f8.Ro},l8=function(a,b,c,d,e,f){g8.call(this,a,b,c,d,e,f);
g.P(this.element,"ytp-caption-window-rollup");this.type=f8.Wo;this.L=this.S=0;this.M=window.NaN;this.ma=null;this.ga=new g.rz(this.ra,433,this);g.K(this,this.ga)},m8=function(a){if(!a.L){var b=g.rd("SPAN");
g.Yt(b,i8(a,a.g.gb));a.A.appendChild(b);b.appendChild(g.vq("M"));var c=b.offsetHeight,d=g.rd("BR");b.appendChild(d);b.appendChild(g.vq("M"));a.L=b.offsetHeight-c;a.A.removeChild(b)}return a.L},n8=function(a,b,c,d){j8.call(this,d);
c=c||g.hk(a).hl||"";c=c.split("_").join("-");this.C=g.lk(a,{hl:c});this.B=b;this.F={};this.A=null},o8=function(a){j8.call(this,a.Tl);
this.A=null;this.C=void 0;this.B=null;this.D=a.captionTranslationLanguages},p8=function(a,b,c,d,e,f){g.J.call(this);
this.G=b;this.B=new J7;this.g=null;this.D=d;this.H=f;this.o=this.A=null;this.J=c;this.C=e||!1;this.F=new g.rz(this.Lx,1E3,this);g.K(this,this.F);b.addEventListener("seekto",this.zr,this);this.zr(b.getCurrentTime());this.Lx()},q8=function(a,b){j8.call(this);
this.C=a;this.W=b;this.A=null;this.B=!1},u8=function(a){g.Su.call(this,a);
g.ni();this.X=g.Y(a);this.B=a.getVideoData();this.ea=g.bY(a);this.W=a;var b=null,c=g.Wt("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Rd(c));this.ca=b;this.C={gb:{}};this.D={gb:{}};this.H=[];this.J={};this.N={};this.M=!1;this.ia="1"==this.B.Qb.cc_auto_caps||"1"==this.X.J.cc_auto_caps;c=b=this.A=this.o=this.G=this.F=this.L=this.da=null;r8(this)||(b=new g.xt(this.bB,void 0,this),g.K(this,b),c=new g.rz(this.hP,2E3,this),g.K(this,c));this.S=b;this.ga=c;this.ba=new g.cG(this);g.K(this,this.ba);
r8(this)||this.ba.V(a,"resize",this.Ks);this.ba.V(a,"onPlaybackAudioChange",this.SK);this.ba.V(a,"crn_captions",this.VR,this);this.ba.V(a,"crx_captions",this.WR,this);s8(this,t8(this,"display-settings")||{});wua(this)&&this.load()},r8=function(a){return"3"!=a.X.B?!1:!!a.W.app.F.g.textTracks},xua=function(a){var b;
a.B.captionTracks.length&&(b=a.g.ci().dv);if("FORCED_ON"==b||1==a.X.Hg||1==a.B.Hg||"alwayson"==a.B.tf("yt:cc"))return!0;if(2==a.X.Hg){var c=t8(a,"module-enabled");if(null!=c)return!!c}return"ON"==b||"on"==a.B.tf("yt:cc")},wua=function(a){return r8(a)?!a.B.Ba:a.B.captionTracks.length&&a.g.ci().Xj?!0:xua(a)},zua=function(a,b){if(!g.Y(a.g).experiments.g("legacy_default_captions")){if(a.o){var c=K7(a.o.g,b||a.ia),d=t8(a,"recent-langs");
if(d){for(var e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(d[e]==t7(c[f]))return c[f];for(e=0;e<d.length;e++)for(var k=d[e].match(yua)[0],f=0;f<c.length;f++){var l=t7(c[f]).match(yua)[0];if(k==l)return c[f]}}return a.G&&a.G.pi?a.G.pi:c[0]||v8(a)}return null}c=null;a.o&&(c=a.o.mw(),!c&&b&&(c=K7(a.o.g,!0)[0]),c||!b&&!a.ia||(d=a.o.g.A,d.length&&(c=vua(a.o,d[0].toString()))),c||(c=v8(a)));return c},v8=function(a){return g.Y(a.g).experiments.g("legacy_default_captions")?a.o.pw():a.G&&a.G.Xj},w8=function(a,
b,c,d){a.loaded&&a.unload();
null!=c&&(a.M=c);a.A=b;a.load(d)},Aua=function(a,b){var c=g.UF(a.ea,!0).height;
if(!c)return null;var d=a.ea.Wa();switch(null!=b.params.wr?b.params.wr:b.params.KP?f8.Wo:1<b.o.length?f8.Ro:f8.Uo){case f8.Ro:return new k8(b,a.C,a.D,c,d.width,d.height);case f8.Wo:return new l8(b,a.C,a.D,c,d.width,d.height);default:return new g8(b,a.C,a.D,c,d.width,d.height)}},s8=function(a,b,c){var d=x8.gb;
a.C={};g.za(a.C,x8);a.C.gb={};g.za(a.C.gb,d);a.D={gb:{}};var e=b.backgroundOverride?a.D:a.C,f=b.background||d.background;T7.test(f);e.gb.background=f;e=b.colorOverride?a.D:a.C;f=b.color||d.color;T7.test(f);e.gb.color=f;e=b.windowColorOverride?a.D:a.C;f=b.windowColor||x8.windowColor;T7.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.C;f=b.backgroundOpacity;null==f&&(f=d.Ie);e.gb.Ie=f;e=b.fontSizeIncrementOverride?a.D:a.C;f=b.fontSizeIncrement;null==f&&(f=d.xi);e.gb.xi=f;e=b.textOpacityOverride?
a.D:a.C;f=b.textOpacity;null==f&&(f=d.gh);e.gb.gh=f;e=b.windowOpacityOverride?a.D:a.C;f=b.windowOpacity;null==f&&(f=x8.zj);e.zj=f;e=b.charEdgeStyleOverride?a.D:a.C;f=b.charEdgeStyle;null==f&&(f=d.yh);e.gb.yh=f;e=b.fontFamilyOverride?a.D:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.gb.fontFamily=f;a.loaded&&a.Ks();c&&y8(a,"display-settings",b)},Cua=function(a,b){if(b&&!a.F){var c=Q7({tj:e8.Oo,
lang:"ru"});a.F=[c,new N7(c.start,c.end-c.start,0,c.id,g.M("YTP_SAMPLE_SUBTITLES"))];g.mY(a.g,a.F)}else!b&&a.F&&(Bua(a,a.F),a.F=null)},Bua=function(a,b){g.CA(a.g,b);
(0,g.L)(b,function(a){g.Fe(this.H,a)},a);
a.S.gk()},Dua=function(a,b){return a&&g.z(a)&&T7.test(a)?a:b},Eua=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},Gua=function(a,b){if(a&&g.z(a)){var c=Fua.indexOf(a);
return-1!=c?c:b}return b},Iua=function(a,b){if(a&&g.z(a)){var c=Hua.indexOf(a);
return-1!=c?c:b}return b},Jua=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?g.Rh(a,-2,4):b},t8=function(a,b){if(!a.ca)return null;
var c;try{c=a.ca.get(b)}catch(d){a.ca.remove(b)}return c},y8=function(a,b,c){if(a.ca)try{a.ca.set(b,c)}catch(d){}};
g.Aj.prototype.J=s7(2,function(a){return a?this.toString()==a.toString():!1});
g.bj.prototype.Hm=s7(1,function(a){return(a=g.cj(this,a))?a.o:0});
g.fj.prototype.Hm=s7(0,function(){return 0});
var Nta=/^#(?:[0-9a-f]{3}){1,2}$/i,Ota=/#(.)(.)(.)/,sua=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,h8={zu:0,NORMAL:1,Cu:2},Hua="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" "),Fua=["none","raised","depressed","uniform","dropShadow"],T7=/^#(?:[0-9a-f]{3}){1,2}$/i;Rta.prototype.B=function(){};var z8={du:0,MY:1,jD:2},qua=["left","right","center"],e8={Oo:0,Xo:1,DZ:2,RT:3},S7={R_:0,Cl:5,ip:6},f8={Uo:0,Ro:1,Wo:2};x7.prototype.clear=function(){this.B=this.o=this.mode=0;this.g=[];this.reset()};
x7.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var Sta=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];y7.prototype.set=function(a){this.g=a};
y7.prototype.get=function(){return this.g};
z7.prototype.clear=function(){this.g=0};
z7.prototype.update=function(){this.g=2==this.g?1:0};
z7.prototype.matches=function(a,b){return 0!=this.g&&a==this.A&&b==this.o};
A7.prototype.jm=function(a){this.cf=a.cf;this.timestamp=a.timestamp;this.g=a.g};
A7.prototype.reset=function(){this.timestamp=this.cf=0;this.g=!1};
B7.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.g=0;this.o=this.Ec=1};
var Xta=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Yta=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Zta=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],$ta=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];H7.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.o=this.D;this.A=this.F;this.g=this.o;var c=(a<<2)+(b<<1)+0;this.D.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
w7.prototype.reset=function(a){this.C=a;this.g.clear();this.B=this.A;this.A.reset(a,0);this.D.reset(a,1)};var x8={windowColor:g.H3.Go,zj:0,textAlign:z8.jD,Fg:7,Ph:50,Xh:100,gb:{background:g.H3.Go,Ie:.75,yh:g.G3.NONE,color:g.H3.mp,fontFamily:g.I3.Vo,xi:0,gh:1,offset:h8.NORMAL}};J7.prototype.contains=function(a){a=g.Pe(this.wa,a);return 0<=a||0>a&&1==(-a-1)%2};
J7.prototype.length=function(){return this.wa.length/2};M7.prototype.reset=function(){};g.p(N7,g.Nr);N7.prototype.toString=function(){return g.Nr.prototype.toString.call(this)};g.p(O7,g.Nr);O7.prototype.toString=function(){return g.Nr.prototype.toString.call(this)};
var P7=0;g.p(R7,M7);R7.prototype.g=function(a){var b=[];this.o||(this.o=Q7(this.A),b.push(this.o));a=g.ka(a.firstChild.childNodes);for(var c=a.next();!c.done;c=a.next())iua(c.value,this.o.id,b);return b};g.p(U7,M7);
U7.prototype.g=function(a){a.firstChild.getAttribute("format");var b,c;a=g.ka(a.firstChild.childNodes);for(var d=a.next();!d.done;d=a.next())switch(d=d.value,d.tagName){case "head":b=d;break;case "body":c=d}if(b)for(b=g.ka(b.childNodes),a=b.next();!a.done;a=b.next())switch(a=a.value,a.tagName){case "pen":var d=a.getAttribute("id"),e=this.o,f={},k=a.getAttribute("p");k&&g.za(f,this.o[k]);k=W7(a,"b");null!=k&&(f.bold=k);k=W7(a,"i");null!=k&&(f.pr=k);k=W7(a,"u");null!=k&&(f.Is=k);k=X7(a,"et");null!=
k&&(f.yh=k);k=X7(a,"of");null!=k&&(f.offset=k);k=Y7(a,"bc");null!=k&&(f.background=k);k=Y7(a,"ec");null!=k&&(f.ov=k);k=Y7(a,"fc");null!=k&&(f.color=k);k=X7(a,"fs");void 0!=k&&k!=g.I3.Tt&&(f.fontFamily=k);k=V7(a,"sz");void 0!=k&&(f.xi=k/100-1);k=V7(a,"bo");void 0!=k&&(f.Ie=k/255);a=V7(a,"fo");void 0!=a&&(f.gh=a/255);e[d]=f;break;case "ws":d=a.getAttribute("id");this.D[d]=jua(this,a);break;case "wp":d=a.getAttribute("id"),this.C[d]=kua(this,a)}b=[];if(c){a={};var d=void 0,l,m;c=g.ka(c.childNodes);for(e=
c.next();!e.done;e=c.next())switch(e=e.value,e.tagName){case "w":m=lua(this,e,!1);(e=a[m.id])&&e.end>m.start&&(e.end=m.start);a[m.id]=m;b.push(m);break;case "p":var n=d,q=l,f=[],k=e.getAttribute("w")||this.A,r=!!W7(e,"a"),u=V7(e,"t")||0,w=V7(e,"d")||5E3;!q&&!r&&n&&n.windowId==k&&n.end>u&&(n.end=u);for(var n=r?S7.ip:S7.Cl,q=this.o[e.getAttribute("p")],A=e.childNodes,F=0;F<A.length;F++){var N=A[F];0<F&&(r=!0);if("s"==N.tagName)var I=N,N=u,Za=w,kb=k,ha=r,nd=n,Bb=I.textContent?I.textContent:"",Nf=this.o[I.getAttribute("p")],
I=V7(I,"t")||0,N=new N7(N+I,Za-I,nd,kb,Bb,ha,Nf);else N=new N7(u,w,n,k,N.textContent||"",r,q);f.push(N)}d&&"\n"==d.text&&(d.text="");if(0<f.length)for(d=f[f.length-1],l=null!=e.getAttribute("d"),f[0].windowId==this.A&&(m=lua(this,e,!0),b.push(m)),e=g.ka(f),f=e.next();!f.done;f=e.next())f=f.value,f.windowId=m.id,m.o.push(f),b.push(f)}}return b};g.p(Z7,Rta);Z7.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+P7++;c=c/1E3-this.F;d=d/1E3-this.F;var k=S7.Cl;a=new O7(c,d-c,k,f,{textAlign:z8.du,Fg:0,Ph:2.5*b,Xh:5.33*a});e=new N7(c,d-c,k,f,e);this.A.push(a);this.A.push(e)}};
g.p(a8,M7);a8.prototype.g=function(a){a=new Z7(a,0,this.B);if(nua(a)){for(;a.g<a.o.byteLength;)for(0==a.version&&(a.D=mua(a)*(1E3/45)),a.C=$7(a);0<a.C;a.C--){var b=$7(a),c=$7(a),d=$7(a);b&4&&(b&3)==this.o&&(0==this.o||1==this.o)&&(b=this.A,b.g.push({time:a.D,type:this.o,gv:c,hv:d,order:b.g.length}))}Wta(this.A,a);return a.A}return[]};
a8.prototype.reset=function(){this.A.clear()};g.p(b8,M7);
b8.prototype.g=function(a,b){for(var c=[],d=a.split(Kua),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Lua.test(f)){var l=A8.exec(f);if(l&&3<=l.length){var m=c8(l[1]),l=c8(l[2])-m,f=f.substring(A8.lastIndex);A8.lastIndex=0;var k=m+k,m=l,n=f,l={};this.o||(this.o=Q7({wr:f8.Uo}),c.push(this.o));var q=this.o,f=S7.Cl;if(0>n.indexOf("<"))c.push(new N7(k,m,f,q.id,n,!1,g.Hb(l)?void 0:l));else{n=n.split(Mua);1!=n.length&&(f=S7.ip,q="_"+Nua++,q=new O7(k,m,f,q,{}),c.push(q));for(var r=k,u=0;u<n.length;u++){var w=n[u];
if(0==u%2){var A=g.Et("<html>"+w+"</html>"),F;A.getElementsByTagName("parsererror").length?(F=A.createElement("span"),F.appendChild(A.createTextNode(w))):F=A.firstChild;oua(this,r,m-(r-k),f,q,0<u,F,l,c)}else r=c8(w)}}}A8.lastIndex=0}}return c};
var Nua=0,Lua=/^NOTE/,Kua=/(?:\r\n|\r|\n){2,}/,A8=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3}).*(?:\r\n|\r|\n)","gm"),Mua=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.p(d8,M7);
d8.prototype.g=function(a){var b=[];this.o||(this.o=Q7(),this.A[this.o.id]=this.o,b.push(this.o));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.A[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=Q7());
var k={};f&&(g.za(k,f.params),f=f.params.gb)&&(k.gb={},g.za(k.gb,f));e.getAttribute("rc")&&(k.Nn=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.Cv=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Fg=0>f||8<f?7:f);e.getAttribute("ah")&&(k.Ph=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.Xh=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.tj=e8.Xo,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.tj=e8.Oo));e.getAttribute("bc")&&(k.gb||(k.gb={}),k.gb.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.gb||(k.gb={}),k.gb.Ie=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.gb||(k.gb={}),k.gb.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.KP=(0,window.parseInt)(e.getAttribute("sd"),10));
f=(0,window.parseInt)(e.getAttribute("d"),10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new O7(c,f,0,e,k)}else c=null}this.A[d]=c;b.push(c);break;case "text":for(d=[],iua(a,this.o.id,d),d=g.ka(d),c=d.next();!c.done;c=d.next())c=c.value,this.A[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.p(g8,g.W);g.h=g8.prototype;g.h.iJ=function(a,b){var c=g.mu(this.element,this.element.parentElement);this.ca=a-c.x;this.da=b-c.y;g.P(this.element,"ytp-dragging")};
g.h.hJ=function(a,b){var c=g.pu(this.element),d=a-this.ca-.02*this.Aa,e=b-this.da-.02*this.va,f=(d+c.width/2)/this.N*3,f=Math.floor(g.Rh(f,0,2)),k=(e+c.height/2)/this.ea*3,k=Math.floor(g.Rh(k,0,2)),l=f+3*k,d=(d+f/2*c.width)/this.N,d=100*g.Rh(d,0,1),c=(e+k/2*c.height)/this.ea,c=100*g.Rh(c,0,1);this.C.params.Fg=l;this.C.params.Xh=c;this.C.params.Ph=d;this.g.Fg=l;this.g.Xh=c;this.g.Ph=d;this.nj(this.B)};
g.h.gJ=function(){g.xh(this.element,"ytp-dragging")};
g.h.Tb=function(){return this.type};
g.h.nj=function(a){var b=Math.min(this.qw(),this.N),c=this.ow();g.Yt(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"96%",height:c?c+"px":"96%",margin:"",transform:""});this.zp(a);a={transform:"",top:"",left:""};b||(a.width="");c||(a.height="");var d=.96*this.g.Ph+2,e=this.g.Fg;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.A.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=
100-d+"%"}b=.96*this.g.Xh+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.A.offsetHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Yt(this.element,a)};
g.h.zp=function(a){var b;for(b=0;b<a.length&&a[b]==this.B[b];b++);if(this.H||this.B.length>b)b=0,this.H=!1,this.B=[],this.F=[],this.G=[],this.D=null,g.yq(this.A);for(;b<a.length;b++)rua(this,a[b])};
g.h.qw=function(){return 0};
g.h.ow=function(){return 0};
g.h.toString=function(){return g.W.prototype.toString.call(this)};g.p(j8,g.J);g.h=j8.prototype;g.h.mw=function(a){var b=this.g.o,c=K7(this.g,!0);a&&0>b&&0<c.length&&(b=0);return 0>b?null:c[b]};
g.h.pw=function(){return null};
g.h.rd=function(){this.o=null};
g.h.O=function(){g.J.prototype.O.call(this);this.rd()};
g.h.cA=function(){return!1};g.p(k8,g8);k8.prototype.zp=function(a){var b=this.C.o;g8.prototype.zp.call(this,a);var c,d;for(a=a.length;a<b.length;a++){var e=b[a],f;d&&e.o==c?f=d:(f={},g.za(f,e.o),g.za(f,Oua),c=e.o,d=f);rua(this,e,f)}};
var Oua={Eq:!0};g.p(l8,g8);l8.prototype.ra=function(){g.xh(this.element,"ytp-rollup-mode");this.nj(this.ma,!0)};
l8.prototype.qw=function(){var a=this.C.params.Cv;if(!this.S&&a){var b=g.rd("SPAN");g.Jq(b,"\u00a0"+(0,g.cc)("\u2014",a)+"\u00a0");g.Yt(b,i8(this,this.g.gb));this.A.appendChild(b);this.S=b.offsetWidth;this.A.removeChild(b)}return this.S};
l8.prototype.ow=function(){return this.C.params.Nn*m8(this)};
l8.prototype.nj=function(a,b){this.ma=a;if(m8(this)){for(var c=0,d=0;d<this.B.length&&c<a.length;d++)this.B[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.B.concat(a.slice(c)));c=1;for(d=0;d<a.length;d++){var e=a[d];g.z(e.text)&&(c+=e.text.split("\n").length-1,e.B||0==d||c++)}c=this.C.params.Nn-c;c!=this.M&&(b||(0,window.isNaN)(this.M)||(g.P(this.element,"ytp-rollup-mode"),this.ga.Oe()),d="",c&&(d="translateY("+Math.ceil(c*m8(this))+"px)"),g.Yt(this.A,"transform",d),this.M=c);g8.prototype.nj.call(this,a)}else g8.prototype.nj.call(this,
a)};g.p(n8,j8);g.h=n8.prototype;g.h.sr=function(a,b){var c=this.ek(a),d=(0,g.B)(function(c){this.A=null;b(c.responseText,a)},this);
this.rd();this.A=g.Nx(c,{format:"RAW",Ib:d,withCredentials:!0});gua(this.g,a)};
g.h.tr=function(a,b,c){var d=this.C;b={type:"list",tlangs:1,v:this.B,fmts:Number(b||!1),vssids:1};this.xx&&(b.asrs=1);d=g.lk(d,b);b=(0,g.B)(function(b){this.A=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.g,e=g.ka(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value,l=m.getAttribute("formats"),n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),u=m.getAttribute("kind"),w=m.getAttribute("id"),A="true"==m.getAttribute("lang_default"),
F="true"==m.getAttribute("cantran"),m=m.getAttribute("vss_id");L7(d,new g.Aj({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:u,id:w,is_servable:!0,is_default:A,is_translateable:F,vss_id:m}))}b=g.ka(b.getElementsByTagName("target"));for(d=b.next();!d.done;d=b.next())q=d.value,d=q.getAttribute("lang_code"),e=q.getAttribute("lang_translated"),l=q.getAttribute("lang_original"),n=q.getAttribute("id"),q="true"==q.getAttribute("lang_default"),d={languageCode:d,languageName:e,languageOriginal:l,
id:n,is_default:q},this.F[d.languageCode]=d.languageName,this.D.push(new g.$c(d))}a()},this);
this.rd();this.A=g.Nx(d,{format:"RAW",Ib:b,withCredentials:!0})};
g.h.ek=function(a){var b=this.C,c={v:this.B,type:"track",lang:a.o,name:a.C,kind:a.B,fmt:a.A};a.g&&(c.tlang=t7(a));return b=g.lk(b,c)};
g.h.rd=function(){j8.prototype.rd.call(this);this.A&&this.A.abort()};
g.h.O=function(){this.rd();j8.prototype.O.call(this)};g.p(o8,j8);g.h=o8.prototype;g.h.sr=function(a,b,c){var d=this.ek(a),e=(0,g.B)(function(c){this.B=null;b(c.responseText,a)},this);
this.rd();this.B=g.Nx(d,{format:"RAW",Ib:e,withCredentials:!0});c&&this.A&&this.A.Xj!=a&&(this.A.pi=a)};
g.h.tr=function(a,b,c,d){this.C=c;if(this.A=d||null)for(b=g.ka(this.A.captionTracks),c=b.next();!c.done;c=b.next())L7(this.g,c.value);a()};
g.h.ek=function(a){var b=a.H,c={};if(this.C||a.A)c.fmt=this.C||"srv"+a.A;a.g&&(c.tlang=a.g.languageCode);return g.lk(b,c)};
g.h.pw=function(){return this.A?this.A.Xj:null};
g.h.mw=function(){return this.A?this.A.pi:null};
g.h.rd=function(){j8.prototype.rd.call(this);this.B&&this.B.abort()};
g.h.O=function(){this.rd();j8.prototype.O.call(this)};g.p(p8,g.J);g.h=p8.prototype;g.h.O=function(){g.J.prototype.O.call(this);this.G.removeEventListener("seekto",this.zr,this);this.o&&this.o.abort()};
g.h.zr=function(a){var b=this.g;this.g=g.ue(this.J.Eh(a).g);b!=this.g&&this.H&&this.H()};
g.h.reset=function(){this.B=new J7;this.o&&(this.o.abort(),this.o=null)};
g.h.Lx=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Fj(a);if(a&&!this.o&&!(this.g&&30<this.g.startTime-this.G.getCurrentTime())){a=this.g;a=a.g.Ao(a);if(!this.B.contains(a.g[0].o)){var b=g.$x(g.gA(a)),c={format:"RAW",qd:(0,g.B)(this.xN,this),withCredentials:!0};this.C&&(c.responseType="arraybuffer");this.o=g.Nx(b,c);this.A=a;var b=this.B,c=this.A.g[0].o,d=g.Pe(b.wa,c);0<=d||0>d&&1==(-d-1)%2||(d=-d-1,0<d&&1==c-b.wa[d-1]&&d<b.wa.length&&1==b.wa[d]-c?(g.Ee(b.wa,d),g.Ee(b.wa,d-1)):0<d&&1==c-b.wa[d-
1]?b.wa[d-1]=c:d<b.wa.length&&1==b.wa[d]-c?b.wa[d]=c:(g.Le(b.wa,d,0,c),g.Le(b.wa,d+1,0,c)))}this.g=g.ue(a.g)}this.F.start()};
g.h.xN=function(a){(this.C?!a.response:!a.responseText)||400<=a.status||null===this.D||(this.C?this.D(a.response,1E3*this.A.g[0].startTime):this.D(a.responseText,1E3*this.A.g[0].startTime));this.o=this.A=null};g.p(q8,j8);g.h=q8.prototype;g.h.sr=function(a,b){this.rd();var c=this.C.g[a.o];if(c){var d=1E3*c.index.Hm(c.index.Bi()),e=g.Y(this.W).Cg;this.A=new p8(0,this.W,c,function(c,e){b(c,a,e,d)},e,(0,g.B)(function(){e&&(this.A&&this.A.reset(),this.o&&this.o.reset(),this.B=!0)},this))}};
g.h.cA=function(){var a=this.B;this.B=!1;return a};
g.h.tr=function(a){g.Y(this.W).Cg?(L7(this.g,new g.Aj({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),L7(this.g,new g.Aj({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}))):L7(this.g,new g.Aj({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()};
g.h.rd=function(){j8.prototype.rd.call(this);this.A&&(this.A.dispose(),this.A=null)};
g.h.ek=function(){return""};
g.h.O=function(){this.rd();j8.prototype.O.call(this)};g.C(u8,g.Su);var yua=/^[^_-]+/;g.h=u8.prototype;g.h.O=function(){r8(this)||Cua(this,!1);u8.P.O.call(this)};
g.h.load=function(a){u8.P.load.call(this);this.G=this.g.ci();if(this.o||a)this.A?(a?this.Mz(a,this.A):3!=this.g.Ya()&&this.o.sr(this.A,(0,g.B)(this.Mz,this),g.Y(this.g).experiments.g("legacy_default_captions")),this.g.ya("captionschanged",u7(this.A))):this.g.ya("onCaptionsTrackListChanged");else{var b;this.B.Ba?b=new q8(this.B.sa,this.g):this.B.captionTracks.length?b=new o8(this.B):b=new n8(this.B.Ul,this.B.videoId,this.B.ni||this.X.ni||this.B.tf("yt:cc_default_lang")||this.X.pa,this.B.Tl);this.o=
b;b.tr((0,g.B)(this.dO,this),!0,r8(this)?"vtt":void 0,this.g.ci())}};
g.h.unload=function(){if(r8(this))for(var a=g.jq("track",void 0,this.ea.g),b=0;b<a.length;b++)g.Bq(a[b]);else g.tz(this.ga),g.oY(this.g,"captions"),this.H=[],this.o&&this.o.rd(),this.F&&g.mY(this.g,this.F),this.Ks();u8.P.unload.call(this);(a=g.aY(this.g.app))&&a.C&&g.hm(a.C.A);this.g.ya("captionschanged",{})};
g.h.dO=function(){var a;if(this.M||xua(this))a=zua(this,this.M);if(r8(this))for(var b=K7(this.o.g,!0),c=0;c<b.length;c++){var d=b[c],e={kind:"subtitles",label:g.Bj(d),srclang:t7(d),src:this.o.ek(d)};d==a&&(e["default"]=1);for(var d=this.W.app.F,e=[g.tq("TRACK",e)],f=0;f<e.length;f++)d.g.appendChild(e[f])}else!this.A&&a&&w8(this,a),this.g.ya("onCaptionsTrackListChanged"),this.g.ya("onApiChange")};
g.h.UP=function(){this.loaded&&!r8(this)&&this.unload()};
g.h.Mz=function(a,b,c,d){if(a){this.o.cA()&&(this.H=[],g.oY(this.W,"captions"),this.S.gk());a=uua(this.o,a,b,c,d);c={trackName:b.C,trackKind:b.B,trackLangCode:t7(b)};b.g&&(c.fromLangCode=b.o);g.gY(this.g,"cc",c);if(this.A!=v8(this)){if(this.M&&!g.tA(this.X)&&!g.$F(this.X)){g.tz(this.ga);b=Q7({Fg:0,Ph:5,Xh:5,Nn:2,textAlign:z8.du,tj:e8.Oo,lang:"ru"});this.L=[b];c=g.M("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON");this.da||(d=new g.iv(g.Ei()),g.K(this,d),this.da=d.element);d=b.end-b.start;var e=g.Bj(this.A);
e&&this.L.push(new N7(b.start,d,0,b.id,e));this.L.push(new N7(b.start,d,0,b.id,c[0]),new N7(b.start,d,0,b.id,this.da,!0),new N7(b.start,d,0,b.id,c[1],!0));g.mY(this.g,this.L);this.ga.Oe()}if(this.M||g.tA(this.X))y8(this,"module-enabled",!0),g.Y(this.g).experiments.g("legacy_default_captions")||(b=t7(this.A),c=t8(this,"recent-langs"),g.qa(c)||(c=[]),g.Fe(c,b),c.unshift(b),3<c.length&&(c.length=3),this.G&&(this.G.pi=this.A));(b=g.aY(this.g.app))&&b.C&&g.hm(b.C.A)}g.mY(this.g,a);this.M=!1}};
g.h.VR=function(a){this.H.push(a);this.S.gk()};
g.h.WR=function(a){g.Fe(this.H,a);this.S.gk()};
g.h.WO=function(a){if(a instanceof O7){var b=this.J[a.id];b&&b.C!=a&&(b.dispose(),delete this.J[a.id],b=null);b||(b=Aua(this,a))&&(this.J[a.id]=b)}else b=a.windowId,this.N[b]||(this.N[b]=[]),this.N[b].push(a)};
g.h.hP=function(){Bua(this,this.L);this.L=null};
g.h.bB=function(){this.S.stop();Qta(this.N);this.H.sort(g.Or);(0,g.L)(this.H,this.WO,this);g.vb(this.J,function(a,b){!this.N[b]||this.F&&-1==this.F.indexOf(a.C)?(a.dispose(),delete this.J[b]):(a.element.parentNode||g.qY(this.g,a.element,5),a.nj(this.N[b]))},this)};
g.h.nA=function(){s8(this,{},!0)};
g.h.nq=function(){var a=x8.gb,a={background:a.background,backgroundOpacity:a.Ie,charEdgeStyle:a.yh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.xi,textOpacity:a.gh,windowColor:x8.windowColor,windowOpacity:x8.zj},b=t8(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Ns=function(a,b){var c={};g.za(c,t8(this,"display-settings"));g.za(c,a);s8(this,c,b);this.g.U("captionssettingschanged")};
g.h.Ks=function(){!r8(this)&&this.loaded&&(g.vb(this.J,function(a,b){a.dispose();delete this.J[b]},this),this.bB())};
g.h.YB=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.Rh(b,-2,4);this.Ns({fontSizeIncrement:c});return c;case "reload":b&&!r8(this)&&w8(this,this.A,!0);break;case "stickyLoading":void 0!=b&&this.X.Db&&y8(this,"module-enabled",!!b);break;case "track":if(!this.o)return{};if(b){if(r8(this))break;if(!g.va(b))break;if(g.Hb(b)){w8(this,null,!0);break}for(var d,e=K7(this.o.g,!0),c=0;c<e.length;c++){var f=e[c];f.o!=b.languageCode||d&&f.D!=b.languageName||(d=b.translationLanguage?
Mta(f,b.translationLanguage):f)}!d||d==this.A&&this.loaded||w8(this,d,!0)}else return this.loaded&&this.A&&this.A!=v8(this)?u7(this.A):{};return"";case "tracklist":return this.o?(0,g.O)(K7(this.o.g,b&&b.includeAsr),function(a){return u7(a)}):[];
case "translationLanguages":return this.o?this.o.D:[];case "displaySettings":d=this.nq();if(g.tA(this.X)&&b&&g.va(b))if(b.reset)this.nA();else{f={};for(c in b)switch(c){case "color":case "background":case "windowColor":f[c]=Dua(b[c],d[c]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[c]=Eua(b[c],d[c]);break;case "charEdgeStyle":f[c]=Gua(b[c],d[c]);break;case "fontSizeIncrement":f[c]=Jua(b[c],d[c]);break;case "fontFamilyOption":f.fontFamily=Iua(b[c],d[c])}for(e in f)f[e+
"Override"]=!0;this.Ns(f,!0);d=this.nq()}d.fontFamilyOption=Hua[d.fontFamily];d.charEdgeStyle=Fua[d.charEdgeStyle];return d;case "sampleSubtitles":r8(this)||void 0==b||Cua(this,!!b);break;case "xmlTrack":b&&this.X.Db&&!r8(this)&&w8(this,new g.Aj({languageName:b.name}),!1,b.xml)}};
g.h.TR=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.X.Db&&a.push("stickyLoading","xmlTrack");return a};
g.h.UR=function(){var a=this.A;return a?{cc:a.F}:{}};
g.h.ZA=function(){this.loaded&&this.A?(y8(this,"module-enabled",!1),this.unload()):w8(this,this.A||zua(this,!0),!0)};
g.h.SK=function(){this.B.captionTracks.length&&(this.loaded&&this.unload(),wua(this)&&this.load())};window._exportCheck==g.Aa&&g.v("ytmod.player.captions",u8,void 0);})(_yt_player);
