(function(g){var window=this;var Pua=function(a,b,c,d){var e=b.Yb();g.Q(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.Sb(c,d?d:"mqdefault.jpg");var k=b instanceof g.xV?g.xg(b.lengthSeconds):null,l=!!f,f=l&&"RD"==g.Zc(f).type,m=b instanceof g.xV?b.Ba:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.M("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Km(c),is_live:m,is_list:l,is_mix:f,background:d?"background-image: url("+
d+")":""};b instanceof g.xW&&(c.playlist_length=b.getLength());a.update(c)},B8=function(a,b){g.QC.call(this,{K:"div",
fa:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.g=a;this.N=!1},C8=function(a){g.jZ.call(this,a,{K:"div",
fa:["ytp-thumbnail-overlay","ytp-channel-overlay"],R:[{K:"div",Y:"ytp-thumbnail-overlay-image",Z:{style:"{{background}}"}},{K:"div",Y:"ytp-thumbnail-overlay-curtain"}]})},D8=function(a){var b=g.Y(a),b=b.A&&!b.F;
g.W.call(this,{K:"a",Y:"ytp-videowall-still",Z:{href:"{{url}}",target:b?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},R:[{K:"div",Y:"ytp-videowall-still-image",Z:{style:"{{background}}"}},{K:"span",Y:"ytp-videowall-still-info",R:[{K:"span",Y:"ytp-videowall-still-info-bg",R:[{K:"span",Y:"ytp-videowall-still-info-content",Z:g.ip||g.xm?{style:"will-change: opacity"}:void 0,R:[{K:"span",Y:"ytp-videowall-still-info-title",R:["{{title}}"]},
{K:"span",Y:"ytp-videowall-still-info-author",R:["{{author_and_views}}"]},{K:"span",Y:"ytp-videowall-still-info-live",R:[g.M("YTP_LIVE")]},{K:"span",Y:"ytp-videowall-still-info-duration",R:["{{duration}}"]}]}]}]},{K:"span",fa:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],R:[{K:"span",Y:"ytp-videowall-still-listlabel-icon"},g.M("YTP_PLAYLIST"),{K:"span",Y:"ytp-videowall-still-listlabel-length",R:[" (",{K:"span",R:["{{playlist_length}}"]},")"]}]},{K:"span",fa:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],R:[{K:"span",Y:"ytp-videowall-still-listlabel-mix-icon"},g.M("YTP_MIX"),{K:"span",Y:"ytp-videowall-still-listlabel-length",R:[" (50+)"]}]}]});this.B=b;this.g=a;this.A=null;this.T("click",this.C);this.T("keypress",this.D);g.Y(a).experiments.g("player_interaction_logging")&&(a=a.app.ba,g.De(a.A,this),b=String(a.G++),this.element.setAttribute("data-visual-id",b),g.Ed(this,(0,g.B)(a.F,a,this)))},E8=function(a){var b={K:"div",
Y:"ytp-upnext",Z:{"aria-label":"{{watch}}"},R:[{K:"div",Y:"ytp-thumbnail-overlay-image",Z:{style:"{{background}}"}},{K:"div",Y:"ytp-thumbnail-overlay-curtain"},{K:"span",Y:"ytp-upnext-top",R:[{K:"span",Y:"ytp-upnext-header",R:[g.M("YTP_PLAYLIST_UP_NEXT")]},{K:"span",Y:"ytp-upnext-title",R:["{{title}}"]},{K:"span",Y:"ytp-upnext-author",R:["{{author}}"]}]},{K:"a",Y:"ytp-upnext-autoplay-icon",Z:{href:"{{url}}","aria-label":g.M("YTP_AUTOPLAY_NEXT")},R:[{K:"svg",Z:{height:"100%",version:"1.1",viewBox:"0 0 98 98",
width:"100%"},R:[{K:"circle",Y:"ytp-svg-autoplay-circle",Z:{cx:"49",cy:"49",fill:"#000","fill-opacity":"0.8",r:"48"}},{K:"circle",Y:"ytp-svg-autoplay-ring",Z:{cx:"-49",cy:"49","fill-opacity":"0",r:"46.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{K:"polygon",Y:"ytp-svg-autoplay-triangle",Z:{fill:"#fff",points:"32,27 72,49 32,71"}}]}]},{K:"span",Y:"ytp-upnext-bottom",R:[{K:"span",Y:"ytp-upnext-cancel"},{K:"span",Y:"ytp-upnext-paused",
R:[g.M("YTP_AUTOPLAY_PAUSED_2")]}]},{K:"span",Y:"ytp-upnext-close"}]};g.W.call(this,b);this.B=null;var c=this.ua["ytp-upnext-cancel"],b=this.ua["ytp-upnext-close"];this.B=new g.W({K:"button",fa:["ytp-upnext-cancel-button","ytp-button"],Z:{tabindex:0,"aria-label":g.M("YTP_AUTOPLAY_CANCEL")},R:[g.M("YTP_CANCEL")]});g.K(this,this.B);this.B.T("click",this.dz,this);this.B.Ha(c);c=new g.W({K:"button",fa:["ytp-upnext-close-button","ytp-button"],Z:{"aria-label":g.M("YTP_AUTOPLAY_CANCEL")}});g.K(this,c);c.T("click",
this.dz,this);c.Ha(b);this.g=a;this.J=this.ua["ytp-svg-autoplay-ring"];this.F=this.D=this.A=this.C=null;this.G=new g.rz(this.dm,5E3,this);g.K(this,this.G);this.H=0;this.V(this.ua["ytp-upnext-autoplay-icon"],"click",this.YM);this.Zy();this.V(a,"autonavvisibility",this.Zy);this.V(a,"mdxnowautoplaying",this.oM);this.V(a,"mdxautoplaycanceled",this.pM);this.V(a,"mdxautoplayupnext",this.eB);3==this.g.Ya()&&(a=(a=g.$X(g.VX(this.g)))?a.mG():null)&&this.eB(a)},Qua=function(a,b){a.C=b;
Pua(a,b,g.Y(a.g),"hqdefault.jpg")},F8=function(a,b){a.A||(g.ls("a11y-announce",g.M("YTP_PLAYLIST_UP_NEXT")+" "+a.C.title),a.H=(0,g.Gu)(),a.A=new g.rz((0,g.B)(a.wp,a,b),25),a.wp(b));
g.xh(a.element,"ytp-upnext-autoplay-paused")},H8=function(a){G8(a);
a.H=(0,g.Gu)();a.wp();g.P(a.element,"ytp-upnext-autoplay-paused")},G8=function(a){a.A&&(a.A.dispose(),a.A=null)},I8=function(a){B8.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.A=new C8(a);g.K(this,this.A);g.qY(this.g,this.A.element,5);this.B=new g.W(["div","ytp-subscribe-card",["img","ytp-author-image",{src:b.profilePicture}],["div","ytp-subscribe-card-right",["div","ytp-author-name",b.author],["div","html5-subscribe-button-container"]]]);g.K(this,this.B);this.B.Ha(this.element);this.C=new g.c3(g.M("YTP_SUBSCRIBE"),null,g.M("YTP_UNSUBSCRIBE"),null,!0,!1,b.gB,b.subscribed,"trailer-endscreen",null,null,a);g.K(this,this.C);this.C.Ha(this.B.ua["html5-subscribe-button-container"]);
this.na()},J8=function(a,b){B8.call(this,a,"videowall-endscreen");
this.da=a;this.ca=b;this.G=0;this.A=[];this.H=this.D=this.C=null;this.J=this.S=!1;this.F=new g.cG(this);g.K(this,this.F);this.L=new g.rz(g.ya(g.P,this.element,"ytp-show-tiles"),0);g.K(this,this.L);var c=new g.W({K:"button",fa:["ytp-button","ytp-endscreen-previous"],Z:{"aria-label":g.M("YTP_PREVIOUS")},R:[g.qi()]});g.K(this,c);c.Ha(this.element);c.T("click",this.eS,this);this.M=new g.iv({K:"div",Y:"ytp-endscreen-content"});g.K(this,this.M);this.M.Ha(this.element);c=new g.W({K:"button",fa:["ytp-button",
"ytp-endscreen-next"],Z:{"aria-label":g.M("YTP_NEXT")},R:[g.ri()]});g.K(this,c);c.Ha(this.element);c.T("click",this.dS,this);this.B=new E8(a);g.K(this,this.B);g.qY(this.g,this.B.element,5);this.na()},Rua=function(a){return(0,g.O)(a.Sf,function(a){return g.VW(a)})},Sua=function(a,b,c){return 0==b&&a.C.length&&(b=c/J8.g,2<=c/J8.g&&2<=b&&g.Y(a.g).experiments.g("video_wall_emphasize_first"))?2*J8.g:J8.g},K8=function(a){var b=a.ca.Dt();
b!=a.S&&(a.S=b,a.g.U("autonavvisibility"))},L8=function(a){g.Su.call(this,a);
g.Xf({});this.o=null;this.isAvailable=!0;this.A=new g.cG(this);g.K(this,this.A);this.B=g.Y(a);Tua(a)?this.o=new J8(this.g,this):this.B.Oa?this.o=new I8(this.g):this.o=new B8(this.g);g.K(this,this.o);g.qY(this.g,this.o.element,5);this.mA();this.A.V(a,"videodatachange",this.mA,this);this.A.V(a,"crn_endscreen",this.IR,this);this.A.V(a,"crx_endscreen",this.JR,this)},Tua=function(a){a=g.Y(a);
return a.ac&&!a.Oa};g.C(B8,g.QC);B8.prototype.create=function(){this.N=!0};
B8.prototype.destroy=function(){this.N=!1};
B8.prototype.Bp=function(){return!1};g.p(C8,g.jZ);C8.prototype.Gb=function(a){a?this.A.show():g.TC(this.A)};g.p(D8,g.W);D8.prototype.jj=function(){var a=this.A.Yb().videoId,b=this.A.getPlaylistId();g.Q2(this.g.app,a,this.A.Gd,b,void 0,void 0)};
D8.prototype.C=function(a){g.tY(this.g,this);g.lZ(a,this.g,!this.g.isFullscreen()&&this.B,this.A.Gd||void 0)&&this.jj()};
D8.prototype.D=function(a){switch(a.keyCode){case 13:case 32:g.vx(a)||(this.jj(),g.xx(a))}};g.p(E8,g.W);g.h=E8.prototype;g.h.dm=function(){this.D&&(this.G.stop(),this.Ea(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.Zy=function(){this.Gb(g.WX(this.g))};
g.h.OM=function(){window.focus();this.dm()};
g.h.na=function(){g.W.prototype.na.call(this)};
g.h.wp=function(a){a=a||g.Y(this.g).experiments.o("autoplay_time")||1E4;var b=Math.min((0,g.Gu)()-this.H,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.g.Ya()?this.select(!0):this.A&&this.A.start()};
g.h.select=function(a){a=void 0===a?!1:a;var b=g.Y(this.g);if(b.experiments.g("autonav_notifications")&&a&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;g.gY(this.g,"xwebnotifications",{permission:c});"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=this.C.Yb(),this.dm(),this.D=new window.Notification(g.M("YTP_PLAYLIST_UP_NEXT"),{body:c.title,icon:c.Sb(b)}),this.F=this.V(this.D,"click",this.OM),this.G.start())}G8(this);
this.g.Dj(!1,a)};
g.h.YM=function(a){!g.Hq(this.B.element,g.qx(a))&&g.lZ(a,this.g)&&this.select()};
g.h.dz=function(){g.hY(this.g,"autonavcancel");g.YX(this.g,!0)};
g.h.oM=function(a){this.g.Ya();this.show();F8(this,a)};
g.h.eB=function(a){this.g.Ya();this.C&&this.C.Yb().videoId==a.Yb().videoId||Qua(this,a)};
g.h.pM=function(){this.g.Ya();G8(this);this.na()};
g.h.O=function(){G8(this);this.dm();g.W.prototype.O.call(this)};g.C(I8,B8);I8.prototype.show=function(){I8.P.show.call(this);this.A.Gb(!0)};
I8.prototype.na=function(){I8.P.na.call(this);this.A.Gb(!1)};g.C(J8,B8);J8.g=2;g.h=J8.prototype;g.h.create=function(){J8.P.create.call(this);var a=this.g.getVideoData();a&&(this.C=Rua(a),this.D=a);this.mh();this.F.V(this.g,"appresize",this.mh);this.F.V(this.g,"videodatachange",this.fS);this.F.V(this.g,"autonavchange",this.bC);this.F.V(this.g,"autonavcancel",this.cS);this.F.V(this.element,"transitionend",this.eO)};
g.h.destroy=function(){g.eG(this.F);g.Gd(this.A);this.A=[];this.C=null;J8.P.destroy.call(this);g.xh(this.element,"ytp-show-tiles");this.L.stop()};
g.h.Bp=function(){return 1!=this.D.autonavState};
g.h.Vn=function(){return g.rY(this.g)&&this.Bp()&&!this.H};
g.h.show=function(){J8.P.show.call(this);g.xh(this.element,"ytp-show-tiles");g.Y(this.g).isMobile?g.sz(this.L):this.L.start();(this.J||this.H&&this.H!=this.D.clientPlaybackNonce)&&g.YX(this.g,!1);var a=this.Vn();g.rY(this.g)&&g.Y(this.g).experiments.g("ui_logging")&&this.ca.log({cancelButtonShow:a?"1":"0",state:this.Bp()?"enabled":"disabled"});a?(K8(this),2==this.D.autonavState?g.Y(this.g).experiments.g("fast_autonav_in_background")&&3==this.g.yo()?this.B.select(!0):F8(this.B):3==this.D.autonavState&&
H8(this.B)):(g.YX(this.g,!0),K8(this))};
g.h.na=function(){J8.P.na.call(this);H8(this.B);K8(this)};
g.h.eO=function(a){g.qx(a)==this.element&&this.mh()};
g.h.mh=function(){if(this.C&&this.C.length){g.P(this.element,"ytp-endscreen-paginate");var a=g.pu(this.element),b=a.width/a.height,c=96/54,d=J8.g,e=J8.g,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(J8.g,2),n,q=Sua(this,0,k),r=Sua(this,1,k);n=l*m+(Math.pow(q,2)-m);n+=Math.pow(r,2)-m;for(n-=m;0<n&&(d<f||e<k);){var u=d/J8.g,w=e/J8.g,A=d<=f-J8.g&&n>=w*m,F=e<=k-J8.g&&n>=u*m;if((u+1)/w*c/b>b/(u/(w+1)*c)&&F)n-=u*m,e+=J8.g;else if(A)n-=w*m,d+=J8.g;else if(F)n-=u*m,e+=J8.g;
else break}c=!1;f=J8.g+q;n>=3*m&&6>=l*m-n&&(e>=f||d>=f)&&r<=J8.g&&(c=!0);n=96*d;m=54*e;b=n/m<b?a.height/m:a.width/n;b=Math.min(b,2);n*=b;m*=b;n*=g.Rh(a.width/n||1,1,1.21);m*=g.Rh(a.height/m||1,1,1.21);n=Math.floor(Math.min(a.width,n));m=Math.floor(Math.min(a.height,m));a=this.M.element;g.ou(a,n,m);g.Yt(a,{marginLeft:n/-2+"px",marginTop:m/-2+"px"});Qua(this.B,this.C[0]);g.Q(this.element,"ytp-endscreen-takeover",this.Vn());K8(this);b=n+4;n=m+4;m=0;f=!1;for(k=0;k<d;k++)for(u=0;u<e;u++)if(w=r>J8.g&&1<=
m&&!f?m+1:m,F=0,c&&k>=d-J8.g&&u>=e-J8.g?F=1:0==u%J8.g&&0==k%J8.g&&(u<q&&k<q?0==u&&0==k&&(F=q):r>J8.g&&u>=e-r&&k>=d-r?u==e-r&&k==d-r&&(f=!0,w=1,F=r):F=J8.g),w=g.Sh(w+this.G,l),0!=F){A=this.A[m];A||(A=new D8(this.g),this.A[m]=A,a.appendChild(A.element));var N=Math.floor(n*u/e),I=Math.floor(b*k/d),Za=Math.floor(n*(u+F)/e)-N-4,kb=Math.floor(b*(k+F)/d)-I-4;g.du(A.element,I,N);g.ou(A.element,kb,Za);g.Yt(A.element,"transitionDelay",(u+k)/20+"s");g.Q(A.element,"ytp-videowall-still-mini",1==F);g.Q(A.element,
"ytp-videowall-still-large",2<F);w=this.C[w];A.A=w;Pua(A,w,g.Y(A.g),g.vh(A.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");F=w.Gd;w=A.g;g.Y(w).experiments.g("player_interaction_logging")&&(w=w.app.ba,F=F&&F.itct,A=A.element.getAttribute("data-visual-id"),g.zD(w,"onLogServerVeCreated",{id:A,tracking_params:F}));m++}g.Q(this.element,"ytp-endscreen-paginate",m<l);for(d=this.A.length-1;d>=m;d--)A=this.A[d],g.Bq(A.element),g.Fd(A);this.A.length=m}};
J8.A=2;J8.o=1.21;g.h=J8.prototype;g.h.fS=function(){var a=this.g.getVideoData();this.D!=a&&(this.G=0,this.C=Rua(a),this.D=a,this.mh())};
g.h.dS=function(){this.G+=this.A.length;this.mh()};
g.h.eS=function(){this.G-=this.A.length;this.mh()};
g.h.tI=function(){return!!this.B.A};
g.h.bC=function(a){1==a?(this.J=!1,this.H=this.D.clientPlaybackNonce,G8(this.B),this.o&&this.mh()):(this.J=!0,this.o&&this.Vn()&&(2==a?F8(this.B):3==a&&H8(this.B)))};
g.h.cS=function(a){if(a){for(a=0;a<this.A.length;a++)g.uY(this.da,this.A[a],!0);this.bC(1)}else this.H=null,this.J=!1;this.mh()};g.C(L8,g.Su);g.h=L8.prototype;g.h.VB=function(){var a=this.g.getVideoData(),b=!Tua(this.g)||!(!a.Sf||!a.Sf.length),a=g.RV(a,"ypc_module"),c=g.DZ(this.g.app);return(b||!1)&&!a&&!c};
g.h.Dt=function(){return(this.o instanceof J8||!1)&&this.o.o&&this.o.Vn()};
g.h.rI=function(){return this.Dt()?this.o.tI():!1};
g.h.O=function(){g.oY(this.g,"endscreen");L8.P.O.call(this)};
g.h.load=function(){L8.P.load.call(this);this.o.show();g.Y(this.g).Oa&&.01>Math.random()&&this.log({trailerEndscreenShow:1})};
g.h.log=function(a){g.gY(this.g,"end",a)};
g.h.unload=function(){L8.P.unload.call(this);this.o.na();this.o.destroy();this.isAvailable=!1};
g.h.IR=function(a){this.VB()&&(this.o.N||this.o.create(),"load"==a.getId()&&this.load())};
g.h.JR=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.mA=function(){g.oY(this.g,"endscreen");var a=Math.max(1E3*(this.g.getVideoData().lengthSeconds-10),0),a=new g.Nr(a,0x8000000000000,{id:"preload",namespace:"endscreen"}),b=new g.Nr(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.mY(this.g,[a,b])};window._exportCheck==g.Aa&&g.v("ytmod.player.endscreen",L8,void 0);})(_yt_player);
